**Tutorial2**


In [1]:
import numpy as np

oneDim = np.array([1.0,2,3,4,5])
print(oneDim)
print("#Dimensions =", oneDim.ndim)
print("Dimension =", oneDim.shape)
print("Size =", oneDim.size)              #size
print("Array type =", oneDim.dtype, '\n') #type

twoDim = np.array([[1,2],[3,4],[5,6],[7,8]])
print(twoDim)
print("#Dimensions =", twoDim.ndim)
print("Dimension =", twoDim.shape)
print("Size =", twoDim.size)
print("Array type =", twoDim.dtype, '\n')

arrFromTuple = np.array([(1,'a',3.0),(2,'b',3.5)])
print(arrFromTuple)
print("#Dimensions =", arrFromTuple.ndim)
print("Dimension =", arrFromTuple.shape)
print("Size =", arrFromTuple.size)

[1. 2. 3. 4. 5.]
#Dimensions = 1
Dimension = (5,)
Size = 5
Array type = float64 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
#Dimensions = 2
Dimension = (4, 2)
Size = 8
Array type = int32 

[['1' 'a' '3.0']
 ['2' 'b' '3.5']]
#Dimensions = 2
Dimension = (2, 3)
Size = 6


In [2]:
print('Array of random numbers from a uniform distribution')
print(np.random.rand(5))

print('\nArray of random numbers from a normal distribution')
print(np.random.randn(5))     # random numbers from a normal distribution

print('\nArray of integers between -10 and 10, with step size of 2')
print(np.arange(-10,10,2))    # similar to range, but returns ndarray instead of list

print('\n2-dimensional array of integers from 0 to 11')
print(np.arange(12).reshape(3,4))  # reshape to a matrix

print('\nArray of values between 0 and 1, split into 10 equally spaced values')
print(np.linspace(0,1,10))    # split interval [0,1] into 10 equally separated values

print('\nArray of values from 10^-3 to 10^3')
print(np.logspace(-3,3,7))

Array of random numbers from a uniform distribution
[0.14701012 0.06635501 0.01633286 0.6027086  0.03651004]

Array of random numbers from a normal distribution
[-1.00715979 -2.05280046 -0.25127001  1.56667548 -1.08869729]

Array of integers between -10 and 10, with step size of 2
[-10  -8  -6  -4  -2   0   2   4   6   8]

2-dimensional array of integers from 0 to 11
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Array of values between 0 and 1, split into 10 equally spaced values
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]

Array of values from 10^-3 to 10^3
[1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03]


In [3]:
print('A 2 x 3 matrix of zeros')
print(np.zeros((2,3)))

print('\nA 3 x 2 matrix of ones')
print(np.ones((3,2)))

print('\nA 3 x 3 identity matrix')
print(np.eye(3))

A 2 x 3 matrix of zeros
[[0. 0. 0.]
 [0. 0. 0.]]

A 3 x 2 matrix of ones
[[1. 1.]
 [1. 1.]
 [1. 1.]]

A 3 x 3 identity matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Element-wise Operations = Hoạt động theo yếu tố


In [4]:
x= np.array([1,2,3,4,5])

print('x =', x)
print('x + 1 =', x+ 1)# +
print('x - 1 =', x- 1)# -
print('x * 2 =', x* 2)# *
print('x // 2 =', x// 2)# //
print('x ** 2 =', x** 2)# ^
print('x % 2 =', x% 2)# %
print('1 / x =', 1/ x)# /

x = [1 2 3 4 5]
x + 1 = [2 3 4 5 6]
x - 1 = [0 1 2 3 4]
x * 2 = [ 2  4  6  8 10]
x // 2 = [0 1 1 2 2]
x ** 2 = [ 1  4  9 16 25]
x % 2 = [1 0 1 0 1]
1 / x = [1.         0.5        0.33333333 0.25       0.2       ]


In [5]:
x= np.array([2,4,6,8,10])
y= np.array([1,2,3,4,5])

print('x =', x)
print('y =', y)
print('x + y =', x+ y)# element-wise +
print('x - y =', x- y)# element-wise -
print('x * y =', x* y)# element-wise *
print('x / y =', x/ y)# element-wise /
print('x // y =', x// y)# element-wise integer //
print('x ** y =', x** y)# element-wise ^




x = [ 2  4  6  8 10]
y = [1 2 3 4 5]
x + y = [ 3  6  9 12 15]
x - y = [1 2 3 4 5]
x * y = [ 2  8 18 32 50]
x / y = [2. 2. 2. 2. 2.]
x // y = [2 2 2 2 2]
x ** y = [     2     16    216   4096 100000]


1.3

In [6]:
x = np.arange(-5,5)
print('Before: x =', x)

y = x[3:5]
print('        y =', y)
y[:] = 1000
print('After : y =', y)
print('        x =', x, '\n')

z = x[3:5].copy()
print('Before: x =', x)
print('        z =', z)
z[:] = 500
print('After : z =', z)
print('        x =', x)

Before: x = [-5 -4 -3 -2 -1  0  1  2  3  4]
        y = [-2 -1]
After : y = [1000 1000]
        x = [  -5   -4   -3 1000 1000    0    1    2    3    4] 

Before: x = [  -5   -4   -3 1000 1000    0    1    2    3    4]
        z = [1000 1000]
After : z = [500 500]
        x = [  -5   -4   -3 1000 1000    0    1    2    3    4]


In [7]:
x= np.arange(-5,5)
print('Before: x =', x)

y= x[3:5]
y[:]= 1000#
print('After : y =', y)
print('        x =', x, '\n')

z= x[3:5].copy()#
print('Before: x =', x)
print('        z =', z)

z[:]= 500
print('After : z =', z)
print('        x =', x)


Before: x = [-5 -4 -3 -2 -1  0  1  2  3  4]
After : y = [1000 1000]
        x = [  -5   -4   -3 1000 1000    0    1    2    3    4] 

Before: x = [  -5   -4   -3 1000 1000    0    1    2    3    4]
        z = [1000 1000]
After : z = [500 500]
        x = [  -5   -4   -3 1000 1000    0    1    2    3    4]


In [8]:
my2dlist= [[1,2,3,4],[5,6,7,8],[9,10,11,12]]# a 2-dim list
print('my2dlist =', my2dlist)
print('my2dlist[2] =', my2dlist[2])
print('my2dlist[:][2] =', my2dlist[:][2])
#print('my2dlist[:,2] =', my2dlist[:,2])     # invalid way to access sublist, will cause syntax error

my2darr= np.array(my2dlist)
print('\nmy2darr =\n', my2darr)

print('my2darr[2][:] =', my2darr[2][:])
print('my2darr[2,:] =', my2darr[2,:])
print('my2darr[:][2] =', my2darr[:][2])
print('my2darr[:,2] =', my2darr[:,2])

print('my2darr[:2,2:] =\n', my2darr[:2,2:])

my2dlist = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
my2dlist[2] = [9, 10, 11, 12]
my2dlist[:][2] = [9, 10, 11, 12]

my2darr =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
my2darr[2][:] = [ 9 10 11 12]
my2darr[2,:] = [ 9 10 11 12]
my2darr[:][2] = [ 9 10 11 12]
my2darr[:,2] = [ 3  7 11]
my2darr[:2,2:] =
 [[3 4]
 [7 8]]


In [9]:
my2darr= np.arange(1,13,1).reshape(3,4)
print('my2darr =\n', my2darr)

divBy3= my2darr[my2darr% 3== 0]
print('\nmy2darr[my2darr % 3 == 0] =', divBy3)

divBy3LastRow= my2darr[2:, my2darr[2,:]% 3== 0]
print('my2darr[2:, my2darr[2,:] % 3 == 0] =', divBy3LastRow)

my2darr =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

my2darr[my2darr % 3 == 0] = [ 3  6  9 12]
my2darr[2:, my2darr[2,:] % 3 == 0] = [[ 9 12]]


In [10]:
my2darr = np.arange(1,13,1).reshape(4,3)
print('my2darr = \n', my2darr)

indices = [2,1,0,3]
print('indices =', indices, '\n')
print('my2darr[indices, :] =\n', my2darr[indices,:])

rowIndex = [0,0,1,2,3]
print('\nrowIndex =', rowIndex)
columnIndex = [0,2,0,1,2]
print('columnIndex =', columnIndex, '\n')
print('my2darr[rowIndex, columnIndex] =', my2darr[rowIndex,columnIndex])

my2darr = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
indices = [2, 1, 0, 3] 

my2darr[indices, :] =
 [[ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]
 [10 11 12]]

rowIndex = [0, 0, 1, 2, 3]
columnIndex = [0, 2, 0, 1, 2] 

my2darr[rowIndex, columnIndex] = [ 1  3  4  8 12]


**1.4 Hàm số học và thống kê Numpy**

In [11]:
y =np.array([-1.4, 0.4, -3.2, 2.5, 3.4])
print('y =', y,  '\n')

print('np.abs(y) =', np.abs(y)) #abs() là trị tuyệt đối
print('np.sqrt(abs(y)) =', np.sqrt(abs(y))) # sqrt() là căn bậc 2
print('np.sign(y) =', np.sign(y)) # biểu thị dấu của phần tử trả về -1 or 1
print('np.exp(y) =', np.exp(y)) # trả về e^y
print('np.sort(y) =', np.sort(y)) # sort là sắp xếp lại thứ tự phần tử trong list theo thứ tự tăng dần

y = [-1.4  0.4 -3.2  2.5  3.4] 

np.abs(y) = [1.4 0.4 3.2 2.5 3.4]
np.sqrt(abs(y)) = [1.18321596 0.63245553 1.78885438 1.58113883 1.84390889]
np.sign(y) = [-1.  1. -1.  1.  1.]
np.exp(y) = [ 0.24659696  1.4918247   0.0407622  12.18249396 29.96410005]
np.sort(y) = [-3.2 -1.4  0.4  2.5  3.4]


In [12]:
x = np.arange(-2,3)
y = np.random.randn(5)
print('x =', x)
print('y =', y, '\n')

print('np.add(x,y) =', np.add(x,y))
print('np.subtract(x,y) =', np.subtract(x,y))
print('np.multiply(x,y) =', np.multiply(x,y))
print('np.divide(x,y) =', np.divide(x,y))
print('np.maximum(x,y) =', np.maximum(x,y))

x = [-2 -1  0  1  2]
y = [-1.47275452 -0.04274987  0.85046664  0.60719101 -1.0043446 ] 

np.add(x,y) = [-3.47275452 -1.04274987  0.85046664  1.60719101  0.9956554 ]
np.subtract(x,y) = [-0.52724548 -0.95725013 -0.85046664  0.39280899  3.0043446 ]
np.multiply(x,y) = [ 2.94550905  0.04274987  0.          0.60719101 -2.00868921]
np.divide(x,y) = [ 1.35799956 23.39188151  0.          1.64692821 -1.99134838]
np.maximum(x,y) = [-1.47275452 -0.04274987  0.85046664  1.          2.        ]
